experiment_name: microgrid_debug

dataset:
  name: microgrid_small
  root_path: ./data/microgrid_lp
  file_extension: .lp
  train_instances:
    - day_001
    - day_002
    - day_003
    - day_004
    - day_005
    - day_006
  validation_instances:
    - day_007
    - day_008
  test_instances:
    - day_009
    - day_010

solver:
  backend: pyscipopt
  time_limit_seconds: 120
  settings:
    limits/time: 120
    limits/nodes: 50000
    presolving/maxrounds: 0
    presolving/maxrestarts: 0
    separating/maxrounds: 0
    separating/maxroundsroot: 1

models:
  node_model: logistic_regression
  cut_model: elastic_net
  retrain_epochs: 1
  calibration: isotonic

guardrails:
  enable_guardrails: true
  no_progress_node_limit: 250
  no_progress_time_seconds: 60
  cut_budget: 50
  node_weight: 0.15

instrumentation:
  enable_node_logging: true
  enable_cut_logging: true

output_directory: ./outputs
